DEVX-2365 (#181)
a fix

diff --git a/.github/workflows/remove-template.yml b/.github/workflows/remove-template.yml
--- a/.github/workflows/remove-template.yml
+++ b/.github/workflows/remove-template.yml
@@ -16,22 +16,19 @@ jobs:
     runs-on: ubuntu-latest
     if: (github.event.label.name == 'remove-template') || (github.event_name == 'issue_comment' && github.event.comment.body == '/remove')
     outputs:
-      npm-package-name: ${{ steps.issue-input.outputs.npm-package-name }}
+      npm-package: ${{ steps.parse-issue-form-body.outputs.npm-package }}
+      error: ${{ steps.parse-issue-form-body.outputs.error }}
     steps:
+      - name: Checkout repository
+        uses: actions/checkout@v2
+      - name: Install dependencies
+        run: npm install
       - name: Parse Issue Form Body
-        uses: peter-murray/issue-forms-body-parser@v2
-        id: issue-payload
-        with:
-          github_token: ${{ secrets.GITHUB_TOKEN }}
-          issue_id: ${{ github.event.issue.number }}
-          separator: "###"
-          label_marker_start: '"'
-          label_marker_end: '"'
-      - name: Parse Issue Payload
-        id: issue-input
+        id: parse-issue-form-body
         run: |
-          npm_package_name=$(echo '${{ steps.issue-payload.outputs.payload }}' | jq '."Name of NPM package"')
-          echo "::set-output name=npm-package-name::$npm_package_name"
+          node src/parse-issue-form-body.js 'removal-request'
+        env:
+          GITHUB_ISSUE_PAYLOAD: ${{ github.event.issue.body }}
   set-owner-repo:
     name: Set the owner and repo name.
     runs-on: ubuntu-latest
@@ -53,7 +50,7 @@ jobs:
     uses: ./.github/workflows/check-permissions-workflow.yml
     with:
       user-login: ${{ github.event.issue.user.login }}
-      npm-package: ${{ needs.parse-issue-form-body.outputs.npm-package-name }}
+      npm-package: ${{ needs.parse-issue-form-body.outputs.npm-package }}
       github-repo-owner: ${{ needs.set-owner-repo.outputs.github-repo-owner }}
       github-repo: ${{ needs.set-owner-repo.outputs.github-repo }}
   remove-from-registry:
@@ -70,13 +67,13 @@ jobs:
         run: npm install
       - name: Change registry.json
         id: run-remove-from-registry
-        run: node src/remove-from-registry.js ${{ needs.parse-issue-form-body.outputs.npm-package-name }}
+        run: node src/remove-from-registry.js ${{ needs.parse-issue-form-body.outputs.npm-package }}
       - name: Commit and push changes
         uses: EndBug/add-and-commit@v8.0.2
         with:
           add: registry.json
           default_author: github_actions
-          message: Remove ${{ needs.parse-issue-form-body.outputs.npm-package-name }} template from Template Registry
+          message: Remove ${{ needs.parse-issue-form-body.outputs.npm-package }} template from Template Registry
           push: true
   success-close-issue:
     name: Close issue
@@ -90,14 +87,15 @@ jobs:
   fail-removal-comment:
     name: Removal failed
     runs-on: ubuntu-latest
-    needs: [check-permissions, remove-from-registry]
-    if: ${{ always() && (needs.remove-from-registry.outputs.error != '' || (needs.check-permissions.outputs.is-admin != 'true' && needs.check-permissions.outputs.is-owner != 'true' && (needs.check-permissions.outputs.is-admin-error != '' || needs.check-permissions.outputs.is-owner-error != ''))) }}
+    needs: [parse-issue-form-body, check-permissions, remove-from-registry]
+    if: ${{ always() && (needs.parse-issue-form-body.result == 'failure' || (needs.parse-issue-form-body.result != 'skipped' && (needs.remove-from-registry.outputs.error != '' || (needs.check-permissions.outputs.is-admin != 'true' && needs.check-permissions.outputs.is-owner != 'true' && (needs.check-permissions.outputs.is-admin-error != '' || needs.check-permissions.outputs.is-owner-error != ''))))) }}
     steps:
       - uses: ben-z/actions-comment-on-issue@1.0.2
         with:
           message: |
             The following checks failed:
 
+            ${{ needs.parse-issue-form-body.outputs.error }}
             ${{ needs.check-permissions.outputs.is-admin-error }}
             ${{ needs.check-permissions.outputs.is-owner-error }}
             ${{ needs.remove-from-registry.outputs.error }}
