DEVX-2181: Create scheduled jobs (#92)
DEVX-2181: Create scheduled jobs

diff --git a/.github/workflows/remove-template.yml b/.github/workflows/remove-template.yml
--- a/.github/workflows/remove-template.yml
+++ b/.github/workflows/remove-template.yml
@@ -32,43 +32,19 @@ jobs:
         run: |
           npm_package_name=$(echo '${{ steps.issue-payload.outputs.payload }}' | jq '."Name of NPM package"')
           echo "::set-output name=npm-package-name::$npm_package_name"
-  validate-admin:
-    name: Check if issue submitted by admin on devx-services team
-    runs-on: ubuntu-latest
-    outputs:
-      error: ${{ steps.check-admin.outputs.error }}
+  check-permissions:
     needs: [parse-issue-form-body]
-    steps:
-      - name: Validate creator of removal request is admin
-        id: check-admin
-        env:
-          USERNAME: ${{ secrets.ADOBE_BOT_GITHUB_USERNAME }}
-          TOKEN: ${{ secrets.ADOBE_BOT_GITHUB_TOKEN }}
-        run: |
-          state=$(curl -u "$USERNAME:$TOKEN" "https://api.github.com/orgs/adobe/teams/devx-services/memberships/${{ github.event.issue.user.login }}" | jq -r '.state')
-          if [ "$state" =  "active" ]; then echo "Submitter is an admin."; else echo "::set-output name=error:::x: Submitter is not an admin belonging to devx-services team. Admins can remove any templates."; fi;
-  validate-requestor:
-    name: Validate matching add-template issue
-    runs-on: ubuntu-latest
-    outputs:
-      error: ${{ steps.check-request-creator.outputs.error }}
-    needs: [parse-issue-form-body, validate-admin]
-    if: ${{ always() && needs.parse-issue-form-body.result == 'success' && needs.validate-admin.outputs.error != '' }}
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v2
-      - name: Install dependencies
-        run: npm install
-      - name: Validate creator of removal request
-        id: check-request-creator
-        run: node src/validate-removal-author.js "${{ github.event.issue.user.login }}" ${{ needs.parse-issue-form-body.outputs.npm-package-name }}
+    uses: ./.github/workflows/check-permissions-workflow.yml
+    with:
+      user-login: ${{ github.event.issue.user.login }}
+      npm-package: ${{ needs.parse-issue-form-body.outputs.npm-package-name }}
   remove-from-registry:
     name: Remove template from registry
     runs-on: ubuntu-latest
     outputs:
       error: ${{ steps.run-remove-from-registry.outputs.error }}
-    needs: [parse-issue-form-body, validate-admin, validate-requestor ]
-    if: ${{ always() && needs.parse-issue-form-body.result == 'success' && (needs.validate-admin.outputs.error == '' || needs.validate-requestor.outputs.error == '') }}
+    needs: [parse-issue-form-body, check-permissions]
+    if: ${{ always() && needs.parse-issue-form-body.result == 'success' && (needs.check-permissions.outputs.is-admin == 'true' || needs.check-permissions.outputs.is-owner == 'true') }}
     steps:
       - name: Checkout repository
         uses: actions/checkout@v2
@@ -82,32 +58,31 @@ jobs:
         with:
           add: registry.json
           default_author: github_actions
-          message: Remove template from registry
+          message: Remove ${{ needs.parse-issue-form-body.outputs.npm-package-name }} template from Template Registry
           push: true
   success-close-issue:
     name: Close issue
     runs-on: ubuntu-latest
     needs: [remove-from-registry]
-    if: ${{ always() && needs.remove-from-registry.result == 'success' }}
     steps:
       - uses: peter-evans/close-issue@v1
         with:
-          comment: "The template has been removed from the registry."
+          comment: "The template has been removed from Template Registry."
           token: ${{ secrets.GITHUB_TOKEN }}
   fail-removal-comment:
     name: Removal failed
     runs-on: ubuntu-latest
-    needs: [validate-requestor, validate-admin, remove-from-registry]
-    if: ${{ always() && (needs.remove-from-registry.outputs.error != '' || needs.validate-requestor.outputs.error != '' || needs.validate-admin.outputs.error != '') }}
+    needs: [check-permissions, remove-from-registry]
+    if: ${{ always() && (needs.remove-from-registry.outputs.error != '' || (needs.check-permissions.outputs.is-admin != 'true' && needs.check-permissions.outputs.is-owner != 'true' && (needs.check-permissions.outputs.is-admin-error != '' || needs.check-permissions.outputs.is-owner-error != ''))) }}
     steps:
       - uses: ben-z/actions-comment-on-issue@1.0.2
         with:
           message: |
             The following checks failed:
-            
-            ${{ needs.validate-admin.outputs.error }}
-            ${{ needs.validate-requestor.outputs.error }}
+
+            ${{ needs.check-permissions.outputs.is-admin-error }}
+            ${{ needs.check-permissions.outputs.is-owner-error }}
             ${{ needs.remove-from-registry.outputs.error }}
-            
+
             Fix all mentioned issues and comment `/remove` to try again.
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
