DEVX-2181: Create scheduled jobs (#182)
DEVX-2181: Create scheduled jobs

diff --git a/.github/workflows/update-template.yml b/.github/workflows/update-template.yml
--- a/.github/workflows/update-template.yml
+++ b/.github/workflows/update-template.yml
@@ -1,4 +1,4 @@
-name: Template Verification
+name: Template Updating
 
 defaults:
   run:
@@ -12,14 +12,14 @@ on:
 
 jobs:
   parse-issue-form-body:
-    name: Parse issue form body
+    name: Parse Issue Form Body
     runs-on: ubuntu-latest
-    if: (github.event.label.name == 'add-template') || (github.event_name == 'issue_comment' && github.event.comment.body == '/check')
+    if: (github.event.label.name == 'update-template') || (github.event_name == 'issue_comment' && github.event.comment.body == '/update')
     outputs:
       github-link: ${{ steps.issue-input.outputs.github-link }}
       npm-package: ${{ steps.issue-input.outputs.npm-package }}
     steps:
-      - name: Parse issue form body
+      - name: Parse Issue Form Body
         uses: peter-murray/issue-forms-body-parser@v2
         id: issue-payload
         with:
@@ -35,15 +35,24 @@ jobs:
           echo "::set-output name=github-link::$github_link"
           npm_package=$(echo '${{ steps.issue-payload.outputs.payload }}' | jq '."Name of NPM package"')
           echo "::set-output name=npm-package::$npm_package"
-  validate-template:
+  check-permissions:
     needs: [parse-issue-form-body]
+    uses: ./.github/workflows/check-permissions-workflow.yml
+    with:
+      user-login: ${{ github.event.issue.user.login }}
+      npm-package: ${{ needs.parse-issue-form-body.outputs.npm-package }}
+  validate-template:
+    needs: [parse-issue-form-body, check-permissions]
+    if: ${{ always() && needs.parse-issue-form-body.result == 'success' && (needs.check-permissions.outputs.is-admin == 'true' || needs.check-permissions.outputs.is-owner == 'true') }}
     uses: ./.github/workflows/validate-template-workflow.yml
     with:
       github-link: ${{ needs.parse-issue-form-body.outputs.github-link }}
       npm-package: ${{ needs.parse-issue-form-body.outputs.npm-package }}
-  add-to-registry:
-    name: Add to Template Registry
+  update-template:
+    name: Update template in registry
     runs-on: ubuntu-latest
+    outputs:
+      error: ${{ steps.run-update-template.outputs.error }}
     needs: [parse-issue-form-body, validate-template]
     if: ${{ always() && (needs.validate-template.outputs.check-npm-package-status == 'success' && needs.validate-template.outputs.check-github-link-status == 'success') }}
     steps:
@@ -51,45 +60,41 @@ jobs:
         uses: actions/checkout@v2
       - name: Install dependencies
         run: npm install
-      - name: Collect metadata and save to registry.json
-        id: run-add-to-registry
+      - name: Change registry.json
+        id: run-update-template
         run: |
           npm v ${{ needs.parse-issue-form-body.outputs.npm-package }} dist.tarball | xargs curl | tar -xz
-          node src/add-to-registry.js $GITHUB_WORKSPACE/package ${{ needs.parse-issue-form-body.outputs.github-link }} ${{ needs.parse-issue-form-body.outputs.npm-package }}
+          node src/update-template.js $GITHUB_WORKSPACE/package ${{ needs.parse-issue-form-body.outputs.github-link }} ${{ needs.parse-issue-form-body.outputs.npm-package }}
       - name: Commit and push changes
         uses: EndBug/add-and-commit@v8
         with:
           add: registry.json
           default_author: github_actions
-          message: Add ${{ needs.parse-issue-form-body.outputs.npm-package }} to Template Registry
+          message: Update ${{ needs.parse-issue-form-body.outputs.npm-package }} template in Template Registry
           push: true
-    outputs:
-      error: ${{ steps.run-add-to-registry.outputs.error }}
   success-close-issue:
     name: Close issue
     runs-on: ubuntu-latest
-    needs: [add-to-registry]
+    needs: [update-template]
     steps:
       - uses: peter-evans/close-issue@v1
         with:
-          comment: ":white_check_mark: Congratulations! Your template has been verified and added to App Builder Template Registry."
+          comment: ":white_check_mark: The template has been updated in Template Registry."
           token: ${{ secrets.GITHUB_TOKEN }}
-  fail-validation-comment:
-    name: Validation failed
+  fail-removal-comment:
+    name: Updating failed
     runs-on: ubuntu-latest
-    needs: [parse-issue-form-body, validate-template, add-to-registry]
-    if: ${{ always() && needs.parse-issue-form-body.result == 'success' && (needs.validate-template.outputs.check-github-link-status != 'success' || needs.add-to-registry.result == 'failure' || needs.add-to-registry.result == 'skipped') }}
+    needs: [check-permissions, update-template]
+    if: ${{ always() && (needs.update-template.outputs.error != '' || (needs.check-permissions.outputs.is-admin != 'true' && needs.check-permissions.outputs.is-owner != 'true' && (needs.check-permissions.outputs.is-admin-error != '' || needs.check-permissions.outputs.is-owner-error != ''))) }}
     steps:
       - uses: ben-z/actions-comment-on-issue@1.0.2
         with:
           message: |
             The following checks failed:
 
-            ${{ needs.validate-template.outputs.check-github-link-error }}
-            ${{ needs.validate-template.outputs.check-npm-package-name-error }}
-            ${{ needs.validate-template.outputs.check-npm-package-metadata-error }}
-            ${{ needs.validate-template.outputs.check-npm-package-error }}
-            ${{ needs.add-to-registry.outputs.error }}
+            ${{ needs.check-permissions.outputs.is-admin-error }}
+            ${{ needs.check-permissions.outputs.is-owner-error }}
+            ${{ needs.update-template.outputs.error }}
 
-            Fix all mentioned issues and comment `/check` to run checks again.
+            Fix all mentioned issues and comment `/update` to try again.
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
