DEVX-2181: Create scheduled jobs - fixes

diff --git a/.github/workflows/validate-template-workflow.yml b/.github/workflows/validate-template-workflow.yml
--- a/.github/workflows/validate-template-workflow.yml
+++ b/.github/workflows/validate-template-workflow.yml
@@ -15,9 +15,9 @@ on:
       check-github-link-status:
         value: ${{ jobs.check-github-link.outputs.status }}
       check-npm-package-name-error:
-        value: ${{ jobs.check-npm-package.outputs.error }}
+        value: ${{ jobs.check-npm-package-name.outputs.error }}
       check-npm-package-name-status:
-        value: ${{ jobs.check-npm-package.outputs.status }}
+        value: ${{ jobs.check-npm-package-name.outputs.status }}
       check-npm-package-metadata-error:
         value: ${{ jobs.check-npm-package-metadata.outputs.error }}
       check-npm-package-metadata-status:
@@ -50,18 +50,18 @@ jobs:
           if [ ${failed} -eq 1 ]; then echo "::set-output name=error:::x: A link to the GitHub repo is incorrect or the GitHub repo is not public."; exit 1; fi;
           echo "::set-output name=status::success";
   check-npm-package-name:
-    name: Check NPM link
+    name: Check NPM package name
     runs-on: ubuntu-latest
     outputs:
       error: ${{ steps.check-npm-package-name.outputs.error }}
       status: ${{ steps.check-npm-package-name.outputs.status }}
     steps:
-      - name: Check NPM link
+      - name: Check NPM package name
         id: check-npm-package-name
         run: |
           failed=0
           npm view ${{ inputs.npm-package }} name || failed=1
-          if [ ${failed} -eq 1 ]; then echo "::set-output name=error:::x: A link to the NPM package is incorrect or the NPM package doesn't exist."; exit 1; fi;
+          if [ ${failed} -eq 1 ]; then echo "::set-output name=error:::x: A NPM package name is incorrect or the NPM package doesn't exist."; exit 1; fi;
           echo "::set-output name=status::success";
   check-npm-package-metadata:
     name: Check NPM package metadata
